//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oantarija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad_solar
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string cantidad_manchas { get; set; }
        public int usuario { get; set; }
        public bool estado { get; set; }
        public Nullable<int> camara { get; set; }
        public Nullable<int> telescopio { get; set; }
        public Nullable<int> software { get; set; }
    
        public virtual usuario usuario1 { get; set; }
        public virtual telescopio telescopio1 { get; set; }
        public virtual camara camara1 { get; set; }
        public virtual software software1 { get; set; }
    }
}
