//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oantarija.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oantarijaEntities : DbContext
    {
        public oantarijaEntities()
            : base("name=oantarijaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boletin> boletin { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<detalle_registro_meteo> detalle_registro_meteo { get; set; }
        public virtual DbSet<detalle_registro_sol> detalle_registro_sol { get; set; }
        public virtual DbSet<disertante> disertante { get; set; }
        public virtual DbSet<envio> envio { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<inscripcion> inscripcion { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<registro_meteo> registro_meteo { get; set; }
        public virtual DbSet<registro_sol> registro_sol { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sala> sala { get; set; }
        public virtual DbSet<suscripcion> suscripcion { get; set; }
        public virtual DbSet<tema> tema { get; set; }
        public virtual DbSet<tipo_grupo> tipo_grupo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<visita> visita { get; set; }
    }
}
