//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oantarija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int cantidad { get; set; }
        public bool vehiculo { get; set; }
        public int horario { get; set; }
        public int usuario { get; set; }
        public int tema { get; set; }
        public int disertante { get; set; }
        public int tipo_grupo { get; set; }
        public int sala { get; set; }
        public bool estado { get; set; }
    
        public virtual disertante disertante1 { get; set; }
        public virtual horario horario1 { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual tema tema1 { get; set; }
        public virtual tipo_grupo tipo_grupo1 { get; set; }
        public virtual sala sala1 { get; set; }
        public virtual visita visita { get; set; }
    }
}
