//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oantarija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visita
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
        public int cantidad_personas { get; set; }
        public string proposito { get; set; }
        public bool vehiculo { get; set; }
        public string placa_vehiculo { get; set; }
        public string tipo_vehiculo { get; set; }
        public string color_vehiculo { get; set; }
        public string procedencia { get; set; }
        public int usuario { get; set; }
        public bool estado { get; set; }
    
        public virtual reserva reserva { get; set; }
    }
}
